language: objective-c
osx_image: xcode7.3
cache:
  - cocoapods
before_install:
  - pod repo update --silent
script:
  - ./Scripts/travis-build-test.sh
after_success:
  - bundle exec slather coverage
  - pod lib lint Contentful.podspec

